### ISSUE TITLE
INSERT BILL

### ISSUE THREAD

**Issue by truongduchuy910** [truongduchuy910/RMS#1]
Ví dụ billId mình đặt chế độ tự sinh, thì khi insert mình set giá trị cho hén là SQL nó không nhận và tự sinh cái khác hay báo lỗi ?

**Comment by cuongnguyen99** [comment]
Vẫn nhận. Vd: Insert into BILL(BillID, DeskID) values('1000','1') thì nó sẽ tạo một bản ghi mới có BillID = 1000 và DeskID = 1 với Payment default = 0, Total default = 0. Nếu đã có BillID = 1000 trước đó rồi thì sẽ báo lỗi và không thêm được

**Comment by cuongnguyen99** [comment]
Giờ có 1 vấn đề là tại một thời điểm thì một bàn chỉ được sử dụng cho 1 bill thôi. Nên là nếu mà khi  chọn bàn để nhập vô bill ấy, thì phải hiện ra các bàn đang trống đã, rồi cho khách chọn 1 trong các bàn trống đó rồi mình mới điền vào BILL.

**Comment by cuongnguyen99** [comment]
Bên csdl t update lại query rồi, vô xem rồi tạo lại cái csdl mới rồi dùng cái query mới update đó luôn.
Nd thay đổi gồm: Bỏ bớt một vài column không cần thiết, bỏ identity ở cái ID. Giờ ID tự nhập chứ không tự sinh nữa.

**Comment by truongduchuy910** [comment]
Cái đó trong code có làm rồi. Chỉ hiển thị ra những bàn available thôi!
Issue close rồi mi bấm Reopen and comment để cho nó hiện lên newfeed

**Comment by cuongnguyen99** [comment]
> Cái đó trong code có làm rồi. Chỉ hiển thị ra những bàn available thôi!
> Issue close rồi mi bấm Reopen and comment để cho nó hiện lên newfeed

Ok sir

**Comment by truongduchuy910** [comment]
như thế này này

**Comment by truongduchuy910** [comment]
Giờ làm liều cho identity tự sinh lại đi.
- Nghĩa là ta insert chừa ra mấy cái tự sinh.
- Sau đó xóa sạch danh sách liên kết và get lại cái mới.
- Vậy là cái mới có ID

**Comment by truongduchuy910** [comment]
Vẫn đảm bảo là nguời dùng tương tác với danh sách liên kết sau đó đồng bộ lên SQL. Và từ SQL đồng bộ ngược lại.

**Comment by cuongnguyen99** [comment]
> Giờ làm liều cho identity tự sinh lại đi.
> 
> * Nghĩa là ta insert chừa ra mấy cái tự sinh.
> * Sau đó xóa sạch danh sách liên kết và get lại cái mới.
> * Vậy là cái mới có ID

Tự sinh tiếp à :v Sao cũng được :v

**Comment by cuongnguyen99** [comment]
3 ngày rồi gửi mail mà thầy châu không rep. đkm :<

**Comment by truongduchuy910** [comment]
Chứ nếu không tự sinh thì Chỗ vũ phải dùng hàm rand() mà thấy mong manh lắm

**Comment by truongduchuy910** [comment]
Đánh dấu quan trọng chwa ?

**Comment by cuongnguyen99** [comment]
ok. Dùng rand() khả năng sinh ra số lặp lại cao lắm

**Comment by truongduchuy910** [comment]
OK
