### ISSUE TITLE
LIỆT KÊ CÁC CÂU LỆNH CẦN DÙNG

### ISSUE THREAD

**Issue by truongduchuy910** [truongduchuy910/RMS#2]
### Menu
- Thêm
- Sửa
- Xóa
- Lấy tất cả
### Bàn 
- Thêm 
- Xóa
- Lấy tất cả
### Bill
- Thêm
- Lấy tất cả
### Gọi món
- Thêm 
- Lấy tất cả

**Comment by truongduchuy910** [comment]
Cần viết chi tiết câu lệnh SQL ra vì mỗi lệnh là một hàm trong models.

**Comment by truongduchuy910** [comment]
Với để ta test CSDL trong SMSS coi có lỗi không nữa

**Comment by cuongnguyen99** [comment]
## Menu
### Thêm món: 
`Insert into MENU(FoodName, Cost) values('Nhập_tên_món','Giá tiền)`
### Sửa
- Sửa giá món: 
`Update MENU Set Cost = 'Giá_mới' Where FoodID = 'ID_món_cần_sửa'`
- Sửa tên món: 
`MENU Set FoodName = 'Tên_mới' Where FoodID = 'ID_món_cần_sửa'`
### Xóa 
`Delete from MENU where FoodID = 'Món_cần_xóa'`
       -->Xóa toàn bộ dữ liệu: Truncate Table MENU
### Chọn tất cả
`Select * From MENU`

**Comment by cuongnguyen99** [comment]
**BÀN**

- Thêm: 
Insert into DESK(DeskID) values ('Mã_bàn_mới')
- Xóa:
Delete from DESK where DeskID = 'Mã bàn cần xóa'

- Lấy tất cả:
Select * From DESK

-Lấy các bàn đang ở trạng thái trống
Select * From DESK where Available = '1'

**Comment by cuongnguyen99** [comment]
**BILL**

- Thêm
Insert into BILL(DeskID) values ('Mã_bàn_trống')
- Lấy tất cả
Select * From BILL
-Update trạng thái đã tính tiền
Update BILL set Payment = '1' where BillID = "Mã bàn đã tính tiền"

**Comment by cuongnguyen99** [comment]
**Gọi món**
-Thêm 
Insert into ADDFOOD values ('Mã_món','Số_lượng','Mã_hóa_đơn_tương_ứng')
-Lấy tất cả
Select * From ADDFOOD
-Xóa món đã gọi (Tính thêm vài trường hợp cho chắc :v)
Delete from ADDFOOD where FoodID = 'Mã_món' and BillID = 'Mã_billid_yêu_cầu_xóa'

**Comment by truongduchuy910** [comment]
Mấy câu lệnh ni vẫn dùng bình thường chứ Cương?
